on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.CLOUD_SQL_CLIENT_CREDENTIALS }}
          instance: cidc-dev-alpha:us-central1:gha-test

      - name: Start PostgreSQL
        shell: bash
        run: |
          sudo systemctl start postgresql.service

      - name: Test PSQL
        shell: bash
        run: |
          PGPASSWORD="${{ secrets.CLOUD_SQL_PASSWORD }}" psql \
          -U "${{ secrets.CLOUD_SQL_USERNAME }}" \
          -d "${{ secrets.CLOUD_SQL_DB }}" \
          -f test.sql
